name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    if: ${{ !contains(join(github.event.commits.*.message), '#skip') }}
    runs-on: ubuntu-20.04
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install 
        run: |
          npm install
          npm install "./phonebook-front"  
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test frontend
        run: npm run test
        working-directory: "./phonebook-front"  
      - name: e2e tests
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run start
          wait-on: http://localhost:3001
      - name: deploy
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fs-phonebook-cicd" 
          heroku_email: ${{secrets.EMAIL}}
  tag_release:
    needs: [simple_deployment_pipeline]
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        